version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: tutorial-db
    restart: always
    ports:
      - 3306:3306
  app:
    volumes:
      - ./php:/php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: tutorial-php
    restart: always
    ports:
      - 8000:8000
